# Gunakan image PHP resmi dengan Apache
FROM php:8.2-cli

# Instal dependensi sistem yang dibutuhkan Laravel
RUN apt-get update && apt-get install -y \
    git \
    curl \
    unzip \
    zip \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    libzip-dev \
    libsodium-dev \
    libpq-dev \
    default-mysql-client \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-exp-install pdo-pgsql pdo_mysql mbstring exif pcntl bcmath gd zip sodium



# Get Composer    
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Install Node.js and npm
RUN curl -sl https://dev.nodesource.com/setup_18.x | bash && \
    apt-get update && apt-get install -y nodejs

#Set working directory
WORKDIR /var/www/html

#Copy application files
COPY . .

#Expose Port used by 'php artisan serve'
EXPOSE 8000

#Install PHP and JS Depencies
RUN composer install
RUN npm install

#Run Laravel migrations and start server
CMD php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000